if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("survminer")
BiocManager::install("tidyverse")
BiocManager::install("preprocessCore")

install.packages("devtools")
devtools::install_github("stemangiola/tidybulk")

install.packages("survival")
install.packages("gapminder")
install.packages("foreach")
install.packages("cowplot")
install.packages("ggsci")
install.packages("GGally")
install.packages("gridExtra")
install.packages("grid")
install.packages("reshape")
install.packages("Hmisc")
install.packages("viridis")
install.packages("furrr")
install.packages('e1071')
install.packages('parallel')
install.packages('microbenchmark')
install.packages('benchmarkme')
install.packages('data.table')

